### ISSUE TITLE
403 forbidden for /presse

### ISSUE THREAD

**Issue by 607nm** [das-labor/repaircafe-bochum.de#14]
http://repaircafe-bochum.de/assets/presse/

**Comment by flanfly** [comment]
Der Server ist so konfiguriert, dass er keine directory listings macht. Kann man zwar anschalten, dazu werde ich aber erst mal nicht kommen. Als Workaround kannst du einfach alle Presseartikel in presse.md verlinken. Das ist IMO auch schöner.
